"""
English-only output enforcement utility.

Prevents any non-English text (especially Persian/Farsi) from reaching the client,
even if accidentally generated by the pipeline.
"""
import re
from typing import Any

NON_EN_RE = re.compile(r"[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF]")


def sanitize_string(s: str) -> str:
    """
    Sanitize a string by replacing any non-English characters with a placeholder.
    
    Args:
        s: Input string
        
    Returns:
        Sanitized string (original if no non-English chars, placeholder otherwise)
    """
    if not s:
        return s
    if NON_EN_RE.search(s):
        return "[ENGLISH ONLY OUTPUT ENFORCED]"
    return s


def enforce_english_only(obj: Any) -> Any:
    """
    Recursively enforce English-only output on any object structure.
    
    Works on:
    - Strings: Replaces non-English chars with placeholder
    - Lists: Recursively processes each element
    - Dicts: Recursively processes each value (keys are preserved)
    - Other types: Returned as-is
    
    Args:
        obj: Any object (str, list, dict, etc.)
        
    Returns:
        Object with all non-English text replaced
    """
    if isinstance(obj, str):
        return sanitize_string(obj)
    if isinstance(obj, list):
        return [enforce_english_only(x) for x in obj]
    if isinstance(obj, dict):
        return {k: enforce_english_only(v) for k, v in obj.items()}
    return obj


